### ISSUE TITLE
Difficult to interact with palette - Quest 1 Link/Standalone

### ISSUE THREAD

**Issue by karunakaruna** [msub2/silk-brush#18]
Using both Oculus Link and standalone, palette selection works intermittently - seems to work better at specific/higher angles.

https://user-images.githubusercontent.com/20630604/108247768-f1c71d00-7107-11eb-938f-84603d9fdcd3.mp4

**Comment by msub2** [comment]
Fixed in 5fe1f1b5e872c9a0a48ed11fc669f2c74a87f0cd
