### ISSUE TITLE
Image 'Ghosting' During Load - Quest 1 Link/Standalone

### ISSUE THREAD

**Issue by karunakaruna** [msub2/silk-brush#20]
Small detail, but during the load of the Tilt Brush logo, moving your head produces a ghost image of the logo. Like a duplicate but 50% opacity. 

During load, it also looks as though a sprite-sheet loads in place of the logo? Let me know if you need a screenshot/video.

**Comment by msub2** [comment]
I'm aware yeah, issue is being tracked in #12. As for the spritesheet, I believe that's just a sample of all the loaded brushes for testing purposes. I didn't think it was the biggest deal but it can probably be removed pretty easily.

**Comment by msub2** [comment]
Ghosting fixed in #23
